Add remote browser feature
elliterate/capybara.py pull request #18
Opened 2017-11-22 05:00 UTC by William-Yeh

This feature exists in Ruby version of Capybara.

2017-11-22 15:51 UTC, elliterate requested changes
Thanks for opening this request! Just one minor nit.

2017-11-22 15:51 UTC, elliterate commented on capybara/selenium/browser.py
> +    if browser_name == "remote":
Can you sort this alphabetically by placing it above the Safari code block?

2017-11-23 06:54 UTC, William-Yeh reviewed
sure!

2017-11-23 07:29 UTC, William-Yeh reviewed
sure!

2017-11-23 19:13 UTC, elliterate approved these changes

2017-11-23 19:14 UTC, merged